name: Daily Battlefield Check
on:
  schedule:
    - cron: '0 12 * * *'  # 12:00 UTC
jobs:
  wake-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST to Webhook
        run: |
          curl -X POST https://battlefield-bot.onrender.com/webhook \
          -H "Content-Type: application/json" \
          -d '{"update_id":123,"message":{"message_id":1,"chat":{"id":52865990,"type":"private"},"date":1696118400,"text":"/check"}}'
